create table sys_oper_log
(
    oper_id        bigint auto_increment comment '日志主键'
        primary key,
    title          varchar(50)   default '' null comment '模块标题',
    business_type  int(2)        default 0  null comment '业务类型（0其它 1新增 2修改 3删除）',
    method         varchar(100)  default '' null comment '方法名称',
    request_method varchar(10)   default '' null comment '请求方式',
    operator_type  int(1)        default 0  null comment '操作类别（0其它 1后台用户 2手机端用户）',
    oper_name      varchar(50)   default '' null comment '操作人员',
    dept_name      varchar(50)   default '' null comment '部门名称',
    oper_url       varchar(255)  default '' null comment '请求URL',
    oper_ip        varchar(128)  default '' null comment '主机地址',
    oper_location  varchar(255)  default '' null comment '操作地点',
    oper_param     varchar(2000) default '' null comment '请求参数',
    json_result    varchar(2000) default '' null comment '返回参数',
    status         int(1)        default 0  null comment '操作状态（0正常 1异常）',
    error_msg      varchar(2000) default '' null comment '错误消息',
    oper_time      datetime                 null comment '操作时间'
)
    comment '操作日志记录';

INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (1, '通知公告', 2, 'com.wkscrm.system.controller.SysNoticeController.edit()', 'PUT', 1, 'admin', null, '/notice', '127.0.0.1', '', '{"noticeContent":"新版本内容","createBy":"admin","createTime":1626372283000,"updateBy":"admin","noticeType":"2","remark":"管理员","params":{},"noticeId":1,"noticeTitle":"温馨提醒：2018-07-01 系统新版本发布啦","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-17 09:22:28');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (2, '通知公告', 2, 'com.wkscrm.system.controller.SysNoticeController.edit()', 'PUT', 1, 'admin', null, '/notice', '127.0.0.1', '', '{"noticeContent":"<p>维护内容</p>","createBy":"admin","createTime":1626372283000,"updateBy":"admin","noticeType":"1","remark":"管理员","params":{},"noticeId":2,"noticeTitle":"维护通知：2018-07-01 系统凌晨维护","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-17 09:22:36');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (3, '通知公告', 2, 'com.wkscrm.system.controller.SysNoticeController.edit()', 'PUT', 1, 'admin', null, '/notice', '127.0.0.1', '', '{"noticeContent":"<p>新版本内容</p>","createBy":"admin","createTime":1626372283000,"updateBy":"admin","noticeType":"2","remark":"管理员","updateTime":1626484948000,"params":{},"noticeId":1,"noticeTitle":"温馨提醒：2018-07-01 新版本发布","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-17 09:22:45');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (4, '菜单管理', 3, 'com.wkscrm.system.controller.SysMenuController.remove()', 'DELETE', 1, 'admin', null, '/menu/4', '127.0.0.1', '', null, '{"msg":"菜单已分配,不允许删除","code":500}', 0, null, '2021-07-17 09:24:51');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (5, '部门管理', 2, 'com.wkscrm.system.controller.SysDeptController.edit()', 'PUT', 1, 'admin', null, '/dept', '127.0.0.1', '', '{"deptName":"唯客","leader":"唯客","deptId":100,"orderNum":"0","delFlag":"0","params":{},"parentId":0,"createBy":"admin","children":[],"createTime":1626372256000,"phone":"15888888888","updateBy":"admin","ancestors":"0","email":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-17 09:26:08');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (6, '菜单管理', 3, 'com.wkscrm.system.controller.SysMenuController.remove()', 'DELETE', 1, 'admin', null, '/menu/4', '127.0.0.1', '', null, '{"msg":"菜单已分配,不允许删除","code":500}', 0, null, '2021-07-17 09:31:10');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (7, '菜单管理', 3, 'com.wkscrm.system.controller.SysMenuController.remove()', 'DELETE', 1, 'admin', null, '/menu/4', '127.0.0.1', '', null, '{"msg":"菜单已分配,不允许删除","code":500}', 0, null, '2021-07-17 09:34:05');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (8, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","orderNum":"6","menuName":"数据库查询","params":{},"parentId":115,"isCache":"0","createBy":"admin","children":[],"isFrame":"1","menuType":"F","perms":"tool:gen:dblist","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-17 11:17:31');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (9, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"system","orderNum":"1","menuName":"系统管理","params":{},"parentId":0,"isCache":"0","path":"system","children":[],"createTime":1626372259000,"updateBy":"admin","isFrame":"1","menuId":1,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:05:39');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (10, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"education","orderNum":"1","menuName":"线索管理","params":{},"parentId":0,"isCache":"0","path":"clue","createBy":"admin","children":[],"isFrame":"1","menuType":"M","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:06:01');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (11, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"eye-open","orderNum":"2","menuName":"客户管理","params":{},"parentId":0,"isCache":"0","path":"customer","createBy":"admin","children":[],"isFrame":"1","menuType":"M","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:06:40');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (12, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"form","orderNum":"3","menuName":"规则管理","params":{},"parentId":0,"isCache":"0","path":"rule","createBy":"admin","children":[],"isFrame":"1","menuType":"M","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:07:17');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (13, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"system","orderNum":"4","menuName":"系统管理","params":{},"parentId":0,"isCache":"0","path":"system","children":[],"createTime":1626372259000,"updateBy":"admin","isFrame":"1","menuId":1,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:07:46');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (14, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"monitor","orderNum":"5","menuName":"系统监控","params":{},"parentId":0,"isCache":"0","path":"monitor","children":[],"createTime":1626372260000,"updateBy":"admin","isFrame":"1","menuId":2,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:08:09');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (15, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"tool","orderNum":"6","menuName":"系统工具","params":{},"parentId":0,"isCache":"0","path":"tool","children":[],"createTime":1626372260000,"updateBy":"admin","isFrame":"1","menuId":3,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:08:14');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (16, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"guide","orderNum":"7","menuName":"若依官网","params":{},"parentId":0,"isCache":"0","path":"http://ruoyi.vip","children":[],"createTime":1626372260000,"updateBy":"admin","isFrame":"0","menuId":4,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:08:29');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (17, '菜单管理', 3, 'com.wkscrm.system.controller.SysMenuController.remove()', 'DELETE', 1, 'admin', null, '/menu/4', '192.168.1.8', '', null, '{"msg":"菜单已分配,不允许删除","code":500}', 0, null, '2021-07-18 09:09:10');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (18, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"guide","orderNum":"7","menuName":"若依官网","params":{},"parentId":0,"isCache":"0","path":"http://ruoyi.vip","children":[],"createTime":1626372260000,"updateBy":"admin","isFrame":"0","menuId":4,"menuType":"M","perms":"","status":"1"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:09:15');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (19, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"checkbox","orderNum":"1","menuName":"标签规则","params":{},"parentId":1069,"isCache":"0","path":"lable","createBy":"admin","children":[],"isFrame":"1","menuType":"C","perms":"rule:lable:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:12:15');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (20, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"email","orderNum":"2","menuName":"下发规则","params":{},"parentId":1069,"isCache":"0","path":"strategy","createBy":"admin","children":[],"isFrame":"1","menuType":"C","perms":"rule:strategy:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:13:46');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (21, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"edit","orderNum":"3","menuName":"数据解析","params":{},"parentId":1069,"isCache":"0","path":"parser","createBy":"admin","children":[],"isFrame":"1","menuType":"C","perms":"rule:parser:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:15:14');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (22, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"checkbox","orderNum":"1","menuName":"数据标签","params":{},"parentId":1069,"isCache":"0","path":"lable","children":[],"createTime":1626570735000,"updateBy":"admin","isFrame":"1","menuId":1070,"menuType":"C","perms":"rule:lable:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:15:30');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (23, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"email","orderNum":"2","menuName":"数据下发","params":{},"parentId":1069,"isCache":"0","path":"strategy","children":[],"createTime":1626570826000,"updateBy":"admin","isFrame":"1","menuId":1071,"menuType":"C","perms":"rule:strategy:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:15:37');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (24, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"date","orderNum":"1","menuName":"客户视图","params":{},"parentId":1068,"isCache":"0","path":"customer","createBy":"admin","children":[],"isFrame":"1","menuType":"C","perms":"customer:customer:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:17:21');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (25, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"cascader","orderNum":"2","menuName":"客户群","params":{},"parentId":1068,"isCache":"0","path":"customerGroup","createBy":"admin","children":[],"isFrame":"1","menuType":"C","perms":"customer:customerGroup:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:18:14');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (26, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"clipboard","orderNum":"1","menuName":"客户线索","params":{},"parentId":1068,"isCache":"0","path":"clue","createBy":"admin","children":[],"isFrame":"1","menuType":"C","perms":"customer:clue:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:19:15');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (27, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"date","orderNum":"2","menuName":"客户视图","params":{},"parentId":1068,"isCache":"0","path":"customer","children":[],"createTime":1626571041000,"updateBy":"admin","isFrame":"1","menuId":1073,"menuType":"C","perms":"customer:customer:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:19:21');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (28, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"cascader","orderNum":"3","menuName":"客户群","params":{},"parentId":1068,"isCache":"0","path":"customerGroup","children":[],"createTime":1626571094000,"updateBy":"admin","isFrame":"1","menuId":1074,"menuType":"C","perms":"customer:customerGroup:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:19:27');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (29, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"drag","orderNum":"1","menuName":"客户线索","params":{},"parentId":1067,"isCache":"0","path":"clue","createBy":"admin","children":[],"isFrame":"1","menuType":"C","perms":"clue:clue:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:21:46');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (30, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"peoples","orderNum":"4","menuName":"数据透视","params":{},"parentId":0,"isCache":"0","path":"report","createBy":"admin","children":[],"isFrame":"1","menuType":"M","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:22:48');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (31, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"system","orderNum":"5","menuName":"系统管理","params":{},"parentId":0,"isCache":"0","path":"system","children":[],"createTime":1626372259000,"updateBy":"admin","isFrame":"1","menuId":1,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:22:55');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (32, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"monitor","orderNum":"6","menuName":"系统监控","params":{},"parentId":0,"isCache":"0","path":"monitor","children":[],"createTime":1626372260000,"updateBy":"admin","isFrame":"1","menuId":2,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:23:04');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (33, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"tool","orderNum":"7","menuName":"系统工具","params":{},"parentId":0,"isCache":"0","path":"tool","children":[],"createTime":1626372260000,"updateBy":"admin","isFrame":"1","menuId":3,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:23:09');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (34, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"guide","orderNum":"8","menuName":"若依官网","params":{},"parentId":0,"isCache":"0","path":"http://ruoyi.vip","children":[],"createTime":1626372260000,"updateBy":"admin","isFrame":"0","menuId":4,"menuType":"M","perms":"","status":"1"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:23:14');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (35, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"exit-fullscreen","orderNum":"1","menuName":"渠道转化率","params":{},"parentId":1077,"isCache":"0","path":"report1","createBy":"admin","children":[],"isFrame":"1","menuType":"C","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:24:14');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (36, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"dashboard","orderNum":"2","menuName":"销售漏斗","params":{},"parentId":1077,"isCache":"0","path":"report2","createBy":"admin","children":[],"isFrame":"1","menuType":"C","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:24:41');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (37, '菜单管理', 3, 'com.wkscrm.system.controller.SysMenuController.remove()', 'DELETE', 1, 'admin', null, '/menu/1075', '192.168.1.8', '', null, '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:25:43');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (38, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"date","orderNum":"1","menuName":"客户视图","params":{},"parentId":1068,"isCache":"0","path":"customer","children":[],"createTime":1626571041000,"updateBy":"admin","isFrame":"1","menuId":1073,"menuType":"C","perms":"customer:customer:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:26:23');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (39, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"cascader","orderNum":"2","menuName":"客户群","params":{},"parentId":1068,"isCache":"0","path":"customerGroup","children":[],"createTime":1626571094000,"updateBy":"admin","isFrame":"1","menuId":1074,"menuType":"C","perms":"customer:customerGroup:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:26:27');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (40, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"chart","orderNum":"3","menuName":"客户群详情","params":{},"parentId":1068,"isCache":"0","path":"group","createBy":"admin","children":[],"isFrame":"1","menuType":"C","perms":"customer:group:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:28:20');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (41, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"form","orderNum":"3","menuName":"数据规则","params":{},"parentId":0,"isCache":"0","path":"rule","children":[],"createTime":1626570437000,"updateBy":"admin","isFrame":"1","menuId":1069,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:30:49');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (42, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"job","orderNum":"2","menuName":"定时任务","params":{},"parentId":0,"isCache":"0","path":"job","component":"monitor/job/index","children":[],"createTime":1626372261000,"updateBy":"admin","isFrame":"1","menuId":110,"menuType":"C","perms":"monitor:job:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:32:17');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (43, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"job","orderNum":"5","menuName":"定时任务","params":{},"parentId":0,"isCache":"0","path":"job","component":"monitor/job/index","children":[],"createTime":1626372261000,"updateBy":"admin","isFrame":"1","menuId":110,"menuType":"C","perms":"monitor:job:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:32:42');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (44, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"system","orderNum":"6","menuName":"系统管理","params":{},"parentId":0,"isCache":"0","path":"system","children":[],"createTime":1626372259000,"updateBy":"admin","isFrame":"1","menuId":1,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:32:48');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (45, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"monitor","orderNum":"7","menuName":"系统监控","params":{},"parentId":0,"isCache":"0","path":"monitor","children":[],"createTime":1626372260000,"updateBy":"admin","isFrame":"1","menuId":2,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:32:55');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (46, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"tool","orderNum":"8","menuName":"系统工具","params":{},"parentId":0,"isCache":"0","path":"tool","children":[],"createTime":1626372260000,"updateBy":"admin","isFrame":"1","menuId":3,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:33:00');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (47, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"guide","orderNum":"9","menuName":"若依官网","params":{},"parentId":0,"isCache":"0","path":"http://ruoyi.vip","children":[],"createTime":1626372260000,"updateBy":"admin","isFrame":"0","menuId":4,"menuType":"M","perms":"","status":"1"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:33:05');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (48, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"druid","orderNum":"5","menuName":"任务管理","params":{},"parentId":0,"isCache":"0","path":"job","createBy":"admin","children":[],"isFrame":"1","menuType":"M","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:34:12');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (49, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"job","orderNum":"5","menuName":"定时任务","params":{},"parentId":1081,"isCache":"0","path":"job","component":"monitor/job/index","children":[],"createTime":1626372261000,"updateBy":"admin","isFrame":"1","menuId":110,"menuType":"C","perms":"monitor:job:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:34:20');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (50, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"cascader","orderNum":"2","menuName":"客户群","params":{},"parentId":1068,"isCache":"0","path":"group","children":[],"createTime":1626571094000,"updateBy":"admin","isFrame":"1","menuId":1074,"menuType":"C","perms":"customer:group:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:36:16');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (51, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '192.168.1.8', '', '{"visible":"0","icon":"chart","orderNum":"3","menuName":"客户群详情","params":{},"parentId":1068,"isCache":"0","path":"groupInfo","children":[],"createTime":1626571700000,"updateBy":"admin","isFrame":"1","menuId":1080,"menuType":"C","perms":"customer:groupInfo:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:36:42');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (52, '菜单管理', 3, 'com.wkscrm.system.controller.SysMenuController.remove()', 'DELETE', 1, 'admin', null, '/menu/4', '192.168.1.8', '', null, '{"msg":"菜单已分配,不允许删除","code":500}', 0, null, '2021-07-18 09:37:30');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (53, '个人信息', 2, 'com.wkscrm.system.controller.SysProfileController.updateProfile()', 'PUT', 1, 'admin', null, '/user/profile', '192.168.1.8', '', '{"roles":[{"flag":false,"roleId":1,"admin":true,"dataScope":"1","params":{},"roleSort":"1","deptCheckStrictly":false,"menuCheckStrictly":false,"roleKey":"admin","roleName":"超级管理员","status":"0"}],"phonenumber":"15888888888","admin":true,"loginDate":1626372258000,"remark":"管理员","delFlag":"0","password":"$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2","loginIp":"127.0.0.1","email":"shixiaoyan@sinosoft.com.cn","nickName":"超级管理员","sex":"1","deptId":103,"avatar":"","dept":{"deptName":"研发部门","leader":"若依","deptId":103,"orderNum":"1","params":{},"parentId":101,"children":[],"status":"0"},"params":{},"userName":"admin","userId":1,"createBy":"admin","createTime":1626372258000,"status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:40:39');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (54, '个人信息', 2, 'com.wkscrm.system.controller.SysProfileController.updateProfile()', 'PUT', 1, 'admin', null, '/user/profile', '192.168.1.8', '', '{"roles":[{"flag":false,"roleId":1,"admin":true,"dataScope":"1","params":{},"roleSort":"1","deptCheckStrictly":false,"menuCheckStrictly":false,"roleKey":"admin","roleName":"超级管理员","status":"0"}],"phonenumber":"15888888888","admin":true,"loginDate":1626372258000,"remark":"管理员","delFlag":"0","password":"$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2","loginIp":"127.0.0.1","email":"shixiaoyan@sinosoft.com.cn","nickName":"超级管理员","sex":"1","deptId":103,"avatar":"","dept":{"deptName":"研发部门","leader":"若依","deptId":103,"orderNum":"1","params":{},"parentId":101,"children":[],"status":"0"},"params":{},"userName":"admin","userId":1,"createBy":"admin","createTime":1626372258000,"status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:42:43');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (55, '用户头像', 2, 'com.wkscrm.system.controller.SysProfileController.avatar()', 'POST', 1, 'admin', null, '/user/profile/avatar', '192.168.1.8', '', '', '{"msg":"文件服务异常，请联系管理员","code":500}', 0, null, '2021-07-18 09:44:30');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (56, '用户头像', 2, 'com.wkscrm.system.controller.SysProfileController.avatar()', 'POST', 1, 'admin', null, '/user/profile/avatar', '192.168.1.8', '', '', '{"msg":"操作成功","imgUrl":"http://127.0.0.1:9300/statics/2021/07/18/d0ff8241-44c1-4750-b1e5-18af3da80832.jpeg","code":200}', 0, null, '2021-07-18 09:45:07');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (57, '代码生成', 6, 'com.wkscrm.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', '', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 09:55:05');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (58, '代码生成', 6, 'com.wkscrm.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', 'clue', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 10:06:09');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (59, '代码生成', 6, 'com.wkscrm.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', 'clue', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 10:07:29');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (60, '代码生成', 6, 'com.wkscrm.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', 'clue', 'null', 1, 'nested exception is org.apache.ibatis.binding.BindingException: Parameter ''array'' not found. Available parameters are [arg1, arg0, param1, param2]', '2021-07-18 10:14:57');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (61, '代码生成', 6, 'com.wkscrm.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', 'clue wkscrm_clue', 'null', 1, 'nested exception is org.apache.ibatis.binding.BindingException: Parameter ''array'' not found. Available parameters are [arg1, arg0, param1, param2]', '2021-07-18 10:21:08');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (62, '代码生成', 6, 'com.wkscrm.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', 'clue wkscrm_clue', 'null', 1, 'nested exception is org.apache.ibatis.binding.BindingException: Parameter ''array'' not found. Available parameters are [arg1, arg0, param1, param2]', '2021-07-18 10:21:31');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (63, '代码生成', 6, 'com.wkscrm.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', 'clue wkscrm_clue', 'null', 1, 'nested exception is org.apache.ibatis.binding.BindingException: Parameter ''array'' not found. Available parameters are [tableNames, param1, tableSchema, param2]', '2021-07-18 10:23:21');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (64, '代码生成', 6, 'com.wkscrm.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', 'clue wkscrm_clue', 'null', 1, 'nested exception is org.apache.ibatis.binding.BindingException: Parameter ''array'' not found. Available parameters are [tableNames, param1, tableSchema, param2]', '2021-07-18 10:23:35');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (65, '代码生成', 6, 'com.wkscrm.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', 'clue wkscrm_clue', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 10:24:56');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (66, '代码生成', 3, 'com.wkscrm.gen.controller.GenController.remove()', 'DELETE', 1, 'admin', null, '/gen/1', '127.0.0.1', '', null, '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 10:27:05');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (67, '代码生成', 6, 'com.wkscrm.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', 'clue wkscrm_clue', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 10:27:13');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (68, '代码生成', 2, 'com.wkscrm.gen.controller.GenController.synchDb()', 'GET', 1, 'admin', null, '/gen/synchDb/clue', '127.0.0.1', '', null, 'null', 1, '同步数据失败，原表结构不存在', '2021-07-18 10:27:39');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (69, '代码生成', 2, 'com.wkscrm.gen.controller.GenController.synchDb()', 'GET', 1, 'admin', null, '/gen/synchDb/clue', '127.0.0.1', '', null, 'null', 1, '同步数据失败，原表结构不存在', '2021-07-18 10:27:52');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (70, '代码生成', 3, 'com.wkscrm.gen.controller.GenController.remove()', 'DELETE', 1, 'admin', null, '/gen/2', '127.0.0.1', '', null, '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 10:40:12');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (71, '代码生成', 6, 'com.wkscrm.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', 'clue wkscrm_clue', 'null', 1, '导入失败：nested exception is org.apache.ibatis.binding.BindingException: Parameter ''tableSchema'' not found. Available parameters are [arg1, arg0, param1, param2]', '2021-07-18 10:43:04');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (72, '代码生成', 6, 'com.wkscrm.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', 'clue wkscrm_clue', 'null', 1, '导入失败：nested exception is org.apache.ibatis.binding.BindingException: Parameter ''tableSchema'' not found. Available parameters are [arg1, arg0, param1, param2]', '2021-07-18 10:45:02');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (73, '代码生成', 6, 'com.wkscrm.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', 'clue wkscrm_clue', '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 10:45:50');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (74, '代码生成', 2, 'com.wkscrm.gen.controller.GenController.synchDb()', 'GET', 1, 'admin', null, '/gen/synchDb/wkscrm_clue/clue', '127.0.0.1', '', null, '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 10:54:02');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (75, '代码生成', 2, 'com.wkscrm.gen.controller.GenController.synchDb()', 'GET', 1, 'admin', null, '/gen/synchDb/wkscrm_clue/clue', '127.0.0.1', '', null, '{"msg":"操作成功","code":200}', 0, null, '2021-07-18 10:54:27');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (76, '代码生成', 8, 'com.wkscrm.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 1, 'Lexical error,   Encountered: <EOF> after : "" at vm/vue/index.vue.vm[line 670, column 0]', '2021-07-18 11:15:05');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (77, '代码生成', 8, 'com.wkscrm.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 1, 'Lexical error,   Encountered: <EOF> after : "" at vm/vue/index.vue.vm[line 670, column 0]', '2021-07-18 11:15:25');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (78, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","icon":"job","orderNum":"3","menuName":"标签管理","params":{},"parentId":0,"isCache":"0","path":"lable","createBy":"admin","children":[],"isFrame":"1","menuType":"M","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-19 06:15:10');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (79, '菜单管理', 1, 'com.wkscrm.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","icon":"international","orderNum":"3","menuName":"数据下发","params":{},"parentId":0,"isCache":"0","path":"strategy","createBy":"admin","children":[],"isFrame":"1","menuType":"M","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-19 06:15:48');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (80, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","icon":"checkbox","orderNum":"1","menuName":"数据标签","params":{},"parentId":1082,"isCache":"0","path":"lable","children":[],"createTime":1626570735000,"updateBy":"admin","isFrame":"1","menuId":1070,"menuType":"C","perms":"rule:lable:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-19 06:16:02');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (81, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","icon":"email","orderNum":"2","menuName":"数据下发","params":{},"parentId":1083,"isCache":"0","path":"strategy","children":[],"createTime":1626570826000,"updateBy":"admin","isFrame":"1","menuId":1071,"menuType":"C","perms":"rule:strategy:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-19 06:16:11');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (82, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","icon":"edit","orderNum":"3","menuName":"解析规则","params":{},"parentId":1069,"isCache":"0","path":"parser","children":[],"createTime":1626570914000,"updateBy":"admin","isFrame":"1","menuId":1072,"menuType":"C","perms":"rule:parser:list","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-19 06:16:27');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (83, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","icon":"job","orderNum":"4","menuName":"标签管理","params":{},"parentId":0,"isCache":"0","path":"lable","children":[],"createTime":1626646510000,"updateBy":"admin","isFrame":"1","menuId":1082,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-19 06:16:57');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (84, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","icon":"form","orderNum":"5","menuName":"数据规则","params":{},"parentId":0,"isCache":"0","path":"rule","children":[],"createTime":1626570437000,"updateBy":"admin","isFrame":"1","menuId":1069,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-19 06:17:07');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (85, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","icon":"peoples","orderNum":"6","menuName":"数据透视","params":{},"parentId":0,"isCache":"0","path":"report","children":[],"createTime":1626571368000,"updateBy":"admin","isFrame":"1","menuId":1077,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-19 06:17:33');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (86, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","icon":"job","orderNum":"3","menuName":"标签管理","params":{},"parentId":0,"isCache":"0","path":"lable","children":[],"createTime":1626646510000,"updateBy":"admin","isFrame":"1","menuId":1082,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-19 06:19:01');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (87, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","icon":"international","orderNum":"4","menuName":"数据下发","params":{},"parentId":0,"isCache":"0","path":"strategy","children":[],"createTime":1626646548000,"updateBy":"admin","isFrame":"1","menuId":1083,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-19 06:19:07');
INSERT INTO wkscrm_system.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (88, '菜单管理', 2, 'com.wkscrm.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","icon":"form","orderNum":"7","menuName":"数据规则","params":{},"parentId":0,"isCache":"0","path":"rule","children":[],"createTime":1626570437000,"updateBy":"admin","isFrame":"1","menuId":1069,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-07-19 06:19:28');