# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER wkscrm

# 挂载目录
VOLUME /home/wkscrm
# 创建目录
RUN mkdir -p /home/wkscrm
# 指定路径
WORKDIR /home/wkscrm
# 复制jar文件到路径
COPY ./jar/wkscrm-modules-file.jar /home/wkscrm/wkscrm-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","ruoyi-modules-file.jar"]
